### ISSUE TITLE
Create custom resolvers for interpreted object types

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#11]
As mentioned in #45, we recently made object types default to `string`. The logic is that, for whatever reason the OAS specifies an unsupported type, we can also interpret that type as a `string`. We need to create a resolver to handle this case.

**Comment by Alan-Cha** [comment]
Is this about stringifying non-scalar response bodies whose schemas are not fully described in the OAS? I believe we handle this case now.
