### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by simax** [strongloop/oasgraph#115]
Not sure if my question is related to this [issue](https://github.com/strongloop/oasgraph/issues/93). My question is about how OASGraph reports errors.

Our API allows you to query product data. If it couldn't find a product it would return a `404` with the accompanying `Json`

```
{
  "meta": {},
  "links": [],
  "validation_result": [
    {
      "member_names": [
        "id"
      ],
      "error_message": "Product '1' not found."
    }
  ]
}
```   

However when using `OASGraph` in `graphiql` we get the following:
```
{
  "errors": [
    {
      "message": "404 - \"{\\\"meta\\\":{},\\\"links\\\":[],\\\"validation_result\\\":[{\\\"member_names\\\":[\\\"id\\\"],\\\"error_message\\\":\\\"Product \\\\u00271\\\\u0027 not found.\\\"}]}\"",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "productAttributes"
      ]
    }
  ],
  "data": {
    "productAttributes": null
  }
}
```

OASGraph wraps our error response into the error array's message field. Which on the surface seems reasonable but it's pretty difficult to read. Do you guys have any thoughts on a way of improving this?
Maybe a config option that allows not wrapping error responses in your error object?

**Comment by ErikWittern** [comment]
@simax Thanks for this issue. Error-handling could indeed be improved in OASGraph. We want to consider the constraints imposed by the GraphQL specification in doing so. I think that the specification does allow for some improvements, though. Details on how errors should be formatted in GraphQL are described here: https://facebook.github.io/graphql/draft/#sec-Errors

The challenge for OASGraph is that REST(-like) APIs have no agreed-upon way to handle errors themselves, e.g., the JSON structure of an error response is arbitrary (and sometimes not defined in the OAS). The GraphQL specification allows for an `extensions` field in a returned error object, though, which again could in the case of OASGraph contain a `rawResponse` field with the JSON you pointed to. The error could then look something like this:

```json
{
  "errors": [
    {
      "message": "404",
      "locations": [ { "line": 2, "column": 3 } ],
      "path": [ "produceAttributes" ],
      "extensions": {
        "rawResponse": {
          "meta": {},
          "links": [],
          "validation_result": [
            {
              "member_names": [
                "id"
              ],
              "error_message": "Product '1' not found."
            }
          ]
        }
      }
    }
  ]
}
```

This would format the error response much better, but still be in line with the GraphQL specification. What do you think?

**Comment by simax** [comment]
Thanks @ErikWittern that looks really good to me, it provides all the information in a very readable format.

**Comment by ErikWittern** [comment]
@simax Great, thanks for the confirmation!

@Alan-Cha What's your take? Simon rightly referenced #93 in this context as well. I have to say that I am less convinced by the idea proposed in that issue, though, as we consider adding multi-OAS-support to OASGraph. I.e., I fear that introducing many additional types (per OAS) as proposed in #93 will increase the risk of collisions and likely lead to "dirty" type names, reducing the ergonomics of the resulting GraphQL interface.

**Comment by Alan-Cha** [comment]
@ErikWittern I like this proposal! I was going to take a crack at it as soon as I finish working on a few other issues. I think this proposal is better than #93 because it is a universal solution and does not depend on the OAS. However, I still think #93 is still interesting.

**Comment by Alan-Cha** [comment]
Sorry for the long delay but we have implemented something similar to the proposed solution! In addition, we have provided the [provideErrorExtensions](https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph#options) option for security reasons.
