### ISSUE TITLE
Injecting different header data on each request?

### ISSUE THREAD

**Issue by amnuts** [strongloop/oasgraph#116]
I know that it's possible to send extra headers when converting OAS to GraphQL by using https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph#options, but this seems like it will only set it up once.  And that's great if you want to add static header, but what about something that would change on every request?  Is it possible to inject something which could change on every request?  In my instance I need to pass the Authorization header which more than likely to change on every request to the '/graphql' end point.

My code currently looks a little something like:

```
module.exports = async function () {
    const app = express();

    // This will always be sent for every request and is static
    let oasOptions = {headers: {'X-Origin': 'GraphQL'}};

    // Would seem that this is a one-time thing done when Express kicks in?
    // The header is likely to be different on every call express takes, though.
    if (app.request.headers && app.request.headers.authorization) {
        oasOptions.headers.authorization = app.request.headers.authorization;
    }

    // I have an NPM package that handles using oasgrah
    const schema = await oas.toGraphQL(oasOptions);

    app.use(cors());
    app.options("*", cors());
    app.use(express.urlencoded({extended: true}));
    app.use(express.json());

    // I need to inject to the resolver every time this is called
    app.use(
        "/graphql",
        graphqlHTTP({
            schema,
            graphiql: process.env.NODE_ENV === "local"
        })
    );

    return app;
};
```

Apologies if I've missed something obvious in the docs or mis-understood how the options bit works.

**Comment by ErikWittern** [comment]
@amnuts A good question! One possible solution is using the `tokenJSONpath` option. It allows to use the [JSON path notation](https://github.com/json-path/JsonPath) to locate the position of a value in the [context](https://graphql.org/learn/execution/#root-fields-resolvers) of the query execution. The exact nature of the context depends on the runtime used with GraphQL - in your case, as it seems you use [express-graphql](https://github.com/graphql/express-graphql), the context would be per default be the Express request object, but can be configured (see [here](https://github.com/graphql/express-graphql#options)).

E.g., you could set:

```javascript
oasOptions.tokenJSONpath = '$.user.token'
```

...to obtain a token from the `user` object of a request.

When using the `tokenJSONpath` option, OASGraph will send the `value` defined using at the path position in a header as follows: `Authorization: `Bearer <value>`. Would this work for you?

**Comment by ErikWittern** [comment]
By the way, you state:

> I have an NPM package that handles using oasgrah

That's super interesting! Would you mind sharing what the package does?

**Comment by amnuts** [comment]
Thank you so much, @ErikWittern!  I've tried out your excellent suggestion and with a little tweak it worked really well and is absolutely perfect for what I needed.  (It kept wanting to add 'Bearer' to the Authorization value even though it was already in the string, so just had to ensure it was stripped first.)

As for our npm package; I'm getting permission to make the skeleton of it a public repo on GitHub, so will be happy to share the code should that be possible.  But right now, it's an internal and private npm package due to having our OAS specification files in there.

Essentially, though, the npm package holds our OAS files for all of our internal services.  There's a small class in the package that allows us to list all the specs, get a specific one, get the server url from the spec depending on what the environment we're running on (which is used in combination with the oasgraph baseUrl option so a random server isn't selected for the resolvers), and also get the combined graphql schema using oasgraph.  It does that by going through all of the oas files in the specs directory, loading them up and converting them one at a time, then uses graphql-tools to join the individual graphql schemas into one big one.

It's a pretty small npm package right now, but has meant we're able to document all our services individually and expose a single schema for an API gateway really easily (thanks to oasgraph).

**Comment by Alan-Cha** [comment]
@amnuts Glad to hear that OASGraph is working so well for you! And thank you so much for going into detail about your npm package! It’s always exciting to hear about our users and how they’re using our library. The prospect of seeing some examples depending on OASGraph takes that feeling to a whole new level so please, if you do get permission, please follow up! We’d absolutely love to see what you’re up to! 

It is interesting to hear that you are trying to create GraphQL interfaces from multiple OASs. Perhaps it would interest you to know that we are currently working on this exact problem right now (check out #82). I already have a basic version with limited collision handling working on my fork and it should be in pulled into the master branch next week.

**Comment by amnuts** [comment]
@Alan-Cha @ErikWittern I've been able to make public our usage of oasgraph that I mentioned, if you fancy checking it out; https://github.com/elucidat/elucidat-npm-skeleton

Hoping to write a blog post about it at some point and how easy it was to achieve with oasgraph.

Thanks for the excellent library and support!

**Comment by Alan-Cha** [comment]
@amnuts Wow, thank you so much for the follow up! This is beyond cool! It is also very well documented! I will definitely check it out later but I already left it a Github star 😄 

If you do make a blog post, please let us know as well! It would be interesting to see what your user experience was like so we know what to improve on in the future!
