### ISSUE TITLE
Add "requestOptions" to createGraphQLSchema's options

### ISSUE THREAD

**Issue by thejibz** [strongloop/oasgraph#117]
Hi guys it's me again :)

I encountered the need to set a proxy to query a backend. The simplest workaround was:
```
//` make the call
    log(`Call ${options.method.toUpperCase()} ${options.url}` +
      `?${querystring.stringify(options.qs)} ` +
      `headers:${JSON.stringify(options.headers)}`)
     
      options.proxy = "myproxy:3128"

    return new Promise((resolve, reject) => {
         request(options, (err, response, body) => {
        if (err) {
```
So I think it could be useful to allow user to specify extra options for the nodejs' request object. Furthermore it is often the case for other lib.

Something along the line of:
`Object.assign(options, requestOptions)`

What's your take on that ?

**Comment by Alan-Cha** [comment]
@thejibz This is a great idea! One concern is that there may be some overlap with preexisting options like `headers` and `qs`. Should we assign some kind of priority or get rid of them entirely in favor of `requestOptions`? Thoughts @ErikWittern?

**Comment by thejibz** [comment]
Regarding overlaping, I agree that these options kind of conflict... Maybe as a first step just add a simple "proxy" option if other request's configs seems non-relevant ? I just made a fork with the new "requestOptions" parameter, it works, but I will wait on a consensus on what to do before making a PR.

**Comment by Alan-Cha** [comment]
I think going for the full `requestOptions` is a good idea. I would like @ErikWittern to weigh in but feel free to submit a PR for us to discuss and iterate on! 😄

**Comment by ErikWittern** [comment]
I agree, this is a good idea. A PR would be highly appreciated.

**Comment by Alan-Cha** [comment]
Accepted PR #135
