### ISSUE TITLE
UsedOTNames

### ISSUE THREAD

**Issue by Alan-Cha** [strongloop/oasgraph#118]
[UsedOTNames](https://github.com/strongloop/oasgraph/blob/fef7438c4f18764e82a6e9b71597f9c2e7a1dec0/packages/oasgraph/src/preprocessor.ts#L34) currently stores uncapitalized OT names.

The [capitalization](https://github.com/strongloop/oasgraph/blob/f013155605878338e58eaf51d7eb4447516caec7/packages/oasgraph/src/preprocessor.ts#L344) should be moved to [before the name is stored](https://github.com/strongloop/oasgraph/blob/f013155605878338e58eaf51d7eb4447516caec7/packages/oasgraph/src/preprocessor.ts#L338).

This is not necessarily a bug. It is a matter of semantics and clarity.

**Comment by SrChip15** [comment]
Please take a look at PR #146 and let me know if everything looks okay.

**Comment by Alan-Cha** [comment]
@SrChip15 Wow, thank you so much for the pull request! It makes me so happy whenever we get one! 

Unfortunately, I think this issue is a little more involved than expected. The changes you made were not sufficient as some tests (`npm test`) failed, but I took the liberty of adapting your commit to make them work again (I am actually quite surprised I had pushing rights...)! 

Thank you so much again!

**Comment by SrChip15** [comment]
@Alan-Cha Your reply is incredibly quick. Thanks!

Last night, I did notice the failing tests from your CI tool, 6 tests from 3 suites were failing. I quickly looked into this and decided to work on it today, since it was getting late for me. Maybe the next time, I'll be more careful. Thanks for fixing this though.

**Comment by Alan-Cha** [comment]
No problem! The tests were failing even though your work looked good so I thought perhaps this "good first issue" was more involved than intended. I didn't want you to spend too much time trying to debug if that is the case so I decided to look into it myself. 

In any case, don't feel discouraged from sending PRs! We love getting them! 😄

**Comment by SrChip15** [comment]
Again, thank you so much for the support and encouragement. Lessons learned - irrespective of the label, be more proactive and diligent while attempting to work on a feature/enhancement/bug.

Yes, for sure, you can expect to see more PRs from me. 😃
