### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by Alan-Cha** [strongloop/oasgraph#120]
The generated GraphQL interface can change depending on the order in which operations are processed and this order is influenced by a number of factors including the node implementation and the structure of the OAS. 

We need to make sure the behavior is consistent as it can affect users and tests. Perhaps we need to sort the OAS before processing?

**Comment by ErikWittern** [comment]
Yes, sorting the operations sounds like a good idea.

**Comment by Alan-Cha** [comment]
Fixed in #138
