### ISSUE TITLE
Nest GraphQL data-types based on path hierarchy

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#13]
Some APIs depict hierarchical paths, e.g.:

* `/orgs/{org}`
* `/orgs/{org}/events`
* `/orgs/{org}/members`

(Taken from the [OAS of the GitHub API](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/github.com/v3/swagger.yaml)).

Such hierarchical path structures provide an opportunity for nesting corresponding GraphQL types. In the above example, in a query for an organization (via `/orgs/{org}`), one should also be able to dig into the `events` or `members` of that organization. For example:

```javascript
{
  orgs (org: "facebook") {
    events {
      ...
    }
    members {
      ...
    }
  }
}
```

To enable such capabilities, the parameter passed to the highest-level resolver needs to be passed on to subsequent resolvers (e.g., using the `ctx`).

**Comment by Alan-Cha** [comment]
Resolved with the [addSubOperations option](https://github.com/strongloop/oasgraph#options).
