### ISSUE TITLE
fillEmptyResponses

### ISSUE THREAD

**Issue by michaelsearles** [strongloop/oasgraph#140]
**Describe the bug**
We have POST and Delete operations that do not return any JSON responses and hence we do not define any response schema in the v2 OAS file in these particular cases. This causes warning in the console when we try to generate the wrapper using OASGraph.

***********************************************************************************************
"warnings": [
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'POST /v1/persons/{concern_role_id}/special_cautions' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'DELETE /v1/persons/{concern_role_id}/special_cautions/{special_caution_id}' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'POST /v1/outcome_plans/{outcome_plan_id}/attachments' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"
    },
  
............

***********************************************************************************************

I have tried setting the option "fillEmptyResponses: true" and this does substantially reduce the number of warnings especially Delete operations, but some still remain.

***********************************************************************************************
"warnings": [
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'POST /v1/persons/{concern_role_id}/special_cautions' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"
    },
    {
      "type": "MissingResponseSchema",
      "message": "Operation 'POST /v1/outcome_plans/{outcome_plan_id}/attachments' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"
    },

........

***********************************************************************************************

**Expected behavior**
Setting the option to fill empty responses should fill all REST resources with empty responses 

**Screenshots**

**Additional context**

**Comment by Alan-Cha** [comment]
Hmmm... this is unexpected behavior. Is it possible to share the OAS (Swagger 2?) or a portion of it? If not, is it possible for you to compare the operations that were affected by the `fillEmptyResponses` option with those that weren't and let us know?

**Comment by michaelsearles** [comment]
Hi Alan, thanks for taking a look at this. I can send on a portion of the OAS file.

**Comment by michaelsearles** [comment]
**************************************** affected by setting option **************************
"type": "MissingResponseSchema",
      "message": "Operation 'DELETE /v5/pg/test_g/{formId}' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"


*************************************** not affected *********************************************

 "type": "MissingResponseSchema",
      "message": "Operation 'POST /v5/testplaces/{role_id}/special_cautions' has no (valid) response schema. You can create placeholder schemas using the fillEmptyResponses option.",
      "mitigation": "Ignore operation"

**Comment by Alan-Cha** [comment]
Sorry for the delay. It's hard to tell what is going on just from the warning messages. Do you have any other warnings? Or is the "no (valid) response schema" the only kind of warning you get?

**Comment by Alan-Cha** [comment]
I finally got around to look at this. Actually, there is no bug! Just misleading documentation.

The option `fillEmptyResponses` is conservative. If selected, OASGraph will _only_ create placeholder schemas for operations that return `204`, aka "no content". In order words, OASGraph will only create placeholder schemas for operations that do not have a response body _on purpose_. 

I will change the warning message and the documentation to reflect this. 

***

Try changing the HTTP codes to `204`s and let us know if you still have any trouble!

**Comment by michaelsearles** [comment]
Thanks Alan, that did the trick.

**Comment by michaelsearles** [comment]
Alan I have a follow up question. I checked RFC7231 and see that a POST resource is not obliged to return a result in the response body and can instead return a 201 response containing a Location header field that provides an identifier for the primary resource created.

This is how we have implemented our POST requests and have to manually change the OAS file.

Enhancement request: Can OASGraph also fill empty responses for 201's as well as 204's because in both cases the response body will be empty ?

**Comment by Alan-Cha** [comment]
To be honest, I'm not well-versed on use patterns regarding HTTP codes but this seems like a reasonable request. 

The 204 restriction is not meant to be a hard limitation. I think that perhaps we should change the behavior of the option so that it will add a placeholder schemas to all operations that do not have a response body but will throw warnings for operations that are not 204 (and 201, I suppose?). How do you fell about that?

**Comment by michaelsearles** [comment]
I think this makes sense to me, but I was wondering if others in the community had an opinion on this?

**Comment by prevuelta** [comment]
I believe there may be other HTTP status codes that fall under this as well?

Eg. 202

**Comment by sbilello** [comment]
How do you setup the option `fillEmptyResponses: true` ?
