### ISSUE TITLE
Cookie Authentication

### ISSUE THREAD

**Issue by jduffy3** [strongloop/oasgraph#141]
**Description**

OpenAPI Spec v3 supports cookie authentication
<https://swagger.io/docs/specification/authentication/cookie-authentication/>

Currently I have to pass LtpaToken2 as a cookie for authentication
However I'm getting the following error
"Cannot send apiKey in '\"cookie\"'"

**To Reproduce**
1. Create an api spec that has the following security setup
 ` "components": {
    "securitySchemes": {
      "CookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "LtpaToken2"
      }
    },
  "security": [{
      "CookieAuth": []
  }],`
2. Spin up oasgraph and try to execute a query
3. See error message

> "message": "Cannot send apiKey in '\"cookie\"'",

**Expected behavior**
Query to be executed successfully

**Comment by Alan-Cha** [comment]
Thanks for filling this issue! 

This is because we currently do not support cookie-based API keys, however we have had cookie support for operation parameters for a while now so I think this should be a relatively simple fix. 

This change should take place [here](https://github.com/strongloop/oasgraph/blob/a039ef5e565f97a9c271b1332b77a5be76d9a417/packages/oasgraph/src/resolver_builder.ts#L441).

**Comment by Alan-Cha** [comment]
Upon completing this fix, we will have support for [every type](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-scheme-object) of API key location.

**Comment by jduffy3** [comment]
Thank you for responding so quickly! 😃  Looking forward to the fix!

**Comment by jduffy3** [comment]
Hey I have a fix in place would it be possible for me to submit a pull request?

I tried to push locally but my access rights are denied. 😢

**Comment by Alan-Cha** [comment]
Yes, of course you may submit a pull request! We love getting pull requests! 

Sorry for not having the time to look at this issue right now (we are very busy until the end of the week) but glad you found a workaround! Please send the PR and we can review it 😄

**Comment by Alan-Cha** [comment]
PR filed: #142

**Comment by jduffy3** [comment]
This issue can now be closed 😄 
https://github.com/strongloop/oasgraph/pull/142
