### ISSUE TITLE
Enable resolution of link parameters beyond response body

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#15]
Currently, OASGraph enables to resolve link parameters which are contained in the previous request's body. However, OAS [supports links to provide parameters from other source](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#linkObject), including parameters of the previous request, or headers. OASGraph should support these cases.

**Comment by Alan-Cha** [comment]
See [run time expression](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#runtimeExpression).
