### ISSUE TITLE
Introduce caching options

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#17]
In some cases, nested GraphQL queries can result in a (large) number of duplicate requests to the wrapped REST-like API. In consequence, many slow HTTP(S) requests need to be performed, backend systems may be burdened, and rate limits may suffer.

One option to avoid this behavior is to introduce caching in the GraphQL layer. Caching would:

* Be optional and disabled by default
* Be applicable to `query` operations only, which we assume to be safe and idempotent

In a first implementation, caching could be enabled globally for all query operations. A maximum cache duration in milliseconds can be provided (with a sensible default). In later implementations, caching could be enabled for selected endpoints only, for example based on the `operationId` property.

For a simple example of how to enable caching based on the URL of a request, consider: https://github.ibm.com/witternj/secure-graph/commit/23ea7287f2651d220092fced20f88d0bad9d6be7

**Comment by Alan-Cha** [comment]
Related to #7

**Comment by ErikWittern** [comment]
Custom resolvers can be used to implement this (see #139).

**Comment by wtrocki** [comment]
Would it be possible to apply per request cache (no problem with the timeout as all caching is limited to single request) 
This can be done by tooling like Facebook DataLoader.

**Comment by Alan-Cha** [comment]
I believe per request caching would be super useful! We simply haven't had the time to look into it as there are usually more critical issues to resolve first. We hoped that implementing the `customResolvers` would be a good compromise.

**Comment by wtrocki** [comment]
@Alan-Cha Leave me with this

**Comment by wtrocki** [comment]
Sadly not
