### ISSUE TITLE
Website in repository description points to HTTP instead of HTTPS

### ISSUE THREAD

**Issue by NicholasBoll** [strongloop/oasgraph#27]
The website of this repository points to http://v4.loopback.io/oasgraph.html instead of https://v4.loopback.io/oasgraph.html

I can't open a PR for this since it is in the metadata of the project and not in any code. I verified the website exists with HTTPS. There is no redirect to ensure HTTPS

**Comment by Alan-Cha** [comment]
Ah okay, I'll make the change right now! Thanks :)
