### ISSUE TITLE
Change our testing system

### ISSUE THREAD

**Issue by Alan-Cha** [strongloop/oasgraph#39]
We currently use the [pre-commit](https://www.npmjs.com/package/pre-commit) NPM module to do our testing. Before every commit, a series of tests will run and if any of the tests fail, then the module will cancel the commit. This restriction can be detrimental to development in certain cases and the testing data is not public. 

We would like change to [Travis CI](https://travis-ci.org). We have tried to do so with pull request #34, however it was unsuccessful because our testing environment is somewhat involved and the changes made did not satisfy the necessary requirements. We need to run multiple processes to run the example API, the graphQL API, and the test queries.

**Comment by ErikWittern** [comment]
I will look into spinning up the API as part of running `npm test`.
