### ISSUE TITLE
Allow to pass URL to CLI to point to web-hosted OAS

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#40]
As proposed by @marioestradarosa in [this comment](https://github.com/strongloop/oasgraph/issues/30#issuecomment-425946419), the CLI could take URL addresses instead of paths to local files and attempt to download the referenced OAS. This feature would allow users to create GraphQL wrappers without having to previously download and store their OAS.

**Comment by marioestradarosa** [comment]
@ErikWittern , I assigned myself to this task, I will write the feature.

**Comment by Alan-Cha** [comment]
@marioestradarosa Wow! Thank you so much! Can't wait to see our first public contribution! 😄

**Comment by Alan-Cha** [comment]
We try to publish when we have new features to offer. I think it's a good time with your latest changes!
