### ISSUE TITLE
Separate oasgraph-cli from oasgraph "core"

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#59]
As discussed in previous comments (https://github.com/strongloop/oasgraph/issues/30#issuecomment-424852958 and https://github.com/strongloop/oasgraph/issues/30#issuecomment-432275971) for issue https://github.com/strongloop/oasgraph/issues/30, there are good arguments for separating the "core" capabilities of OASGraph (`oasgraph`) from the ones needed for the CLI (`oasgraph-cli`), including:

* Cleaner separation of dependencies, i.e.,. avoiding `oasgraph` to have to depend on code only needed for the CLI, while still allowing `oasgraph-cli` to make all dependencies explicit.
* Improving the getting-started experience by enabling global installation of `oasgraph-cli`.
* Reducing the attack-/vulnerability-surface for applications that use `oasgraph` as a library (in production).

As suggested by @bajtos , we can consider keeping the code in a single repository, though, relying on tools like [`lerna`](https://github.com/lerna/lerna).

**Comment by Alan-Cha** [comment]
Closed with 505888bbd498f69025b95b3e3b64ec94a255e0b8
