### ISSUE TITLE
Question: OASGraph ignores patch?

### ISSUE THREAD

**Issue by dougal83** [strongloop/oasgraph#60]
Looking at the combination loopback 4 and oasgraph, it seems that PATCH is used by lb4 for openapi.json and subsequently ignored by oasgraph.  I noticed that PUT is picked up by oasgraph and generates a mutation.

Will lb4 and oasgraph teams be coordinating their approach to openapi application?  The direction looks very promising.

**Comment by Alan-Cha** [comment]
Good catch! This seems to be an oversight [here](https://github.com/strongloop/oasgraph/blob/0de1ab1eeaa5b8401e78bddf4742cba817ecf002/src/oas_3_tools.ts#L64), where we define the CRUD operations. 

And yes, the LB4 and OASGraph teams are working towards a more seamless developer experience! 😄

**Comment by dougal83** [comment]
Easily missed considering use of patch is not as prevalent.  Thank you for quick resolution.  Keep up the good work.  Closing issue.
