### ISSUE TITLE
nested same property didn't work

### ISSUE THREAD

**Issue by candysmurf** [strongloop/oasgraph#66]
**Describe the bug**
Same labels didn't work

**To Reproduce**
Input snippet 
```sh
components:
  schemas:
    RedfishError:
      properties:
        error:
          properties:
            '@Message.ExtendedInfo':
              description: An array of message objects describing one or more error
                message(s).
              items:
                $ref: Message.v1_0_6.yaml#/components/schemas/Message
              type: array
            code:
              description: A string indicating a specific MessageId from the message
                registry.
              type: string
            message:
              description: A human-readable error message corresponding to the message
                in the message registry.
              type: string
          type: object
      type: object
info:
  contact:
    name: DMTF
    url: https://www.dmtf.org/standards/redfish
```

Error
```sh
▶ oasgraph /Users/xxx/Downloads/DSP8010_2018.2/openapi/openapi.yaml --save
/Users/xxx/Downloads/DSP8010_2018.2/openapi/openapi.yaml:6
          properties:
          ^^^^^^^^^^

SyntaxError: Label 'properties' has already been declared
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)

```

**Comment by Alan-Cha** [comment]
I believe the issue here is that OASGraph does not support YAML. Try converting to JSON and try again. 

***

According to the spec: "An OpenAPI document that conforms to the OpenAPI Specification is itself a JSON object, which may be represented either in JSON or YAML format." [Source](https://swagger.io/specification/)
 
I will file another issue for that one. We have tested YAML OASs before but we converted them before feeding them to OASGraph. We should make a OASGraph do the conversion itself. Should be an easy fix!

***

I also tried converting the `RedfishError` schema object and adding the snippit into one of our example fixtures and it worked fine.

**Comment by Alan-Cha** [comment]
Sorry for the issues! We just recently released OASGraph to the public and so even though we think the project is relatively robust, there is still a lot of work to do. Thanks for taking an interest in it and trying to make it work. 

If you want more direct feedback, you could try our [Gitter chatroom](https://gitter.im/oasgraph/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) and I could help walk you through any obstacles that come your way.

**Comment by candysmurf** [comment]
@Alan-Cha, thanks for your quick and excellent support. I'll join your Gitter chatroom. All those external links refer to a component yaml object. I'm not sure how many yamls I would need to convert. I'll try to convert the main one and see if it works. If you can support yaml, that would be great. Yaml is the super set of json for large docs.

**Comment by candysmurf** [comment]
We can close this one as you opened an issue for it. I'm looking forward to your yaml support. thanks
