### ISSUE TITLE
Do not publish package-lock.json

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#68]
As proposed by our StrongLoop colleagues, and as argued for in [this issue](https://github.com/strongloop/loopback-next/issues/1579), publishing the package-lock.json file can shield us from noticing if a dependency breaks OASGraph. We should therefore remove stop publishing it in the future.

**Comment by Alan-Cha** [comment]
Closed with 505888bbd498f69025b95b3e3b64ec94a255e0b8
