### ISSUE TITLE
Move library documentation

### ISSUE THREAD

**Issue by ErikWittern** [strongloop/oasgraph#71]
Currently, the documentation for OASGraph the library is contained in the root README of the repository. The unfortunate side effect is that no proper documentation shows up on the OASGraph npm page:

![image](https://user-images.githubusercontent.com/1745998/48141021-f1c4eb00-e277-11e8-8f73-2abc6f2d10e0.png)

We should move the library documentation to `/packages/oasgraph/README.md` for this to change, and keep only the bare minimum documentation in the root README.

**Comment by Alan-Cha** [comment]
Yeah, I noticed this too. I was wondering if we should add some badges or copy the OAS to GraphQL image to the other READMEs so they look less barren. However, I think your suggestion is better. I think it makes sense. 

We can use [OAS-kit](https://github.com/Mermade/oas-kit) as a model for our own repository.

**Comment by ErikWittern** [comment]
This is achieved with the above commits.
