### ISSUE TITLE
Access to resolvers?

### ISSUE THREAD

**Issue by tbrannam** [strongloop/oasgraph#78]
Is it possible to consume the resolvers directly?
It would be useful to be able to fetch data via the generated interface.

**Comment by ErikWittern** [comment]
OASGraph is creating resolvers as part of building the GraphQL schema object as described [here](https://graphql.org/graphql-js/type/#graphqlschema). There may be ways to manually execute resolvers in a GraphQL schema, but there is no specific mechanisms for this provided by OASGraph.
