### ISSUE TITLE
links parameters are not resolved

### ISSUE THREAD

**Issue by cupofcoffe** [strongloop/oasgraph#85]
Hello,

Is there any way for links parameters to support next scenario:

 "parameters": {
		  "search": "fieldname_{$response.body#/$..id}"
},

it is possible in OpenAPI specification, with the results "fieldname_123" 
but unfortunately your jsonPath validation can only send real Id value as the parameter, and can not add hardcoded constants. is there any trick so this can be possible? path. and query. seems also does not do the trick.

Thanks in advance

**Comment by Alan-Cha** [comment]
Hi! Thanks for the issue!

Unfortunately, we currently do not handle these cases but we will try to as soon as possible! Links are critical to OASGraph so it is important to every case. This is currently at the top of the priority list. Related issues: #15 and #19 

***

I am embarrassed to say I was not aware of the string concatenation pattern you presented in this issue. Thank you for pointing that out as well. 

"Expressions can be embedded into string values by surrounding the expression with {} curly braces." [Source.](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#linkObject)
