### ISSUE TITLE
Error is clear on which line it caused the issue

### ISSUE THREAD

**Issue by candysmurf** [strongloop/oasgraph#94]
**Describe the bug**
Error didn't tell much, such as which line is the root cause

**To Reproduce**
1. oasgraph  xyz.json
2. error

```sh
$oasgraph xyz.json
(node:5994) ExperimentalWarning: The http2 module is an experimental API.
OASGraph creation event error:  Invalid type array for format uri
```

**Expected behavior**
A clear and concise description of which line caused this error

**Comment by Alan-Cha** [comment]
Would you be able to provide the OAS?

Otherwise, I assume the problem has to do with a weirdly formatted URI that the http2 module cannot parse. I know that's not that helpful but it's hard to debug without knowing the OAS.

**Comment by Alan-Cha** [comment]
Do you still need help with this issue? Otherwise, I will close the issue.
